[document]
title = "texforge-capabilites"
author = "Jheison M"
template = "general"

[build]
entry = "main.tex"
bibliography = "bib/references.bib"

[highlight]
theme = "one-light"
style = "light"

[highlight.by_lang]
bash = "dark"
