//! syntect wrapper: theme tables, language lookup and per-block tokenization.
//!
//! Everything here is pure Rust and offline: the syntax set is a committed,
//! pre-dumped asset (`assets/highlight/syntaxes.syntect`, regenerated by
//! `scripts/regen-syntaxes`), and both themes are built from Rust constants —
//! no plist/yaml loading, no `onig`, no network at build time or at runtime.
//!
//! Caching (the R2 content-hash idea) was considered and rejected: the only
//! real cost is one `SyntaxSet::from_reader` per process, guarded by a
//! process-lifetime `OnceLock` that already spans watch-mode rebuilds.
//! Per-block content caching would add file I/O and staleness risk for
//! microseconds of re-tokenizing.

use std::io::Cursor;
use std::sync::OnceLock;

use anyhow::{anyhow, Result};
use syntect::easy::HighlightLines;
use syntect::highlighting::{Color, StyleModifier, Theme, ThemeItem, ThemeSettings};
use syntect::parsing::{SyntaxReference, SyntaxSet};

/// The curated dump: `include_bytes!` keeps it in the binary as compressed
/// bytes (zlib inside), never as parsed data at rest.
const SYNTAXES: &[u8] = include_bytes!("../../assets/highlight/syntaxes.syntect");

/// One token of one line. `color` is `None` exactly when the token renders in
/// the theme's base foreground — emit.rs leaves such runs unwrapped, which
/// keeps the emitted LaTeX small and the base text plain black.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Span {
    pub text: String,
    pub color: Option<Rgb>,
}

/// An 8-bit RGB triple, the only colour vocabulary texforge emits.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Rgb {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

impl Rgb {
    pub const fn new(r: u8, g: u8, b: u8) -> Self {
        Self { r, g, b }
    }

    /// The colour's LaTeX name: `tfxcol` + lowercase hex, so identical
    /// colours always share one `\definecolor` line.
    pub fn name(&self) -> String {
        format!("tfxcol{:02x}{:02x}{:02x}", self.r, self.g, self.b)
    }

    /// `{r,g,b}` as `color.sty`'s `rgb` fractions, three decimals.
    pub fn to_rgb_list(self) -> String {
        format!(
            "{:.3},{:.3},{:.3}",
            f64::from(self.r) / 255.0,
            f64::from(self.g) / 255.0,
            f64::from(self.b) / 255.0
        )
    }
}

impl From<Color> for Rgb {
    fn from(c: Color) -> Self {
        Self::new(c.r, c.g, c.b)
    }
}

impl From<Rgb> for Color {
    fn from(rgb: Rgb) -> Self {
        Self {
            r: rgb.r,
            g: rgb.g,
            b: rgb.b,
            a: 0xFF,
        }
    }
}

/// The two supported light themes. Dark themes are refused by design: the
/// emitted LaTeX never paints a block background (there is no page to paint
/// on), so a white-on-dark palette would print as white on paper.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HighlightTheme {
    Github,
    OneLight,
}

impl Default for HighlightTheme {
    /// `github` — the documented default.
    fn default() -> Self {
        Self::Github
    }
}

/// The valid theme names, in the order errors should list them.
pub const VALID_THEME_NAMES: [&str; 2] = ["github", "one-light"];

impl HighlightTheme {
    /// Parse a theme name from `project.toml`'s `[highlight] theme`. An
    /// unknown name fails the build, naming the offending value and every
    /// valid alternative — mirroring `DiagramStyle::parse`.
    pub fn parse(name: &str) -> Result<Self> {
        match name {
            "github" => Ok(Self::Github),
            "one-light" => Ok(Self::OneLight),
            other => anyhow::bail!(
                "Unknown code theme '{other}' — valid themes are: {}",
                VALID_THEME_NAMES.join(", ")
            ),
        }
    }

    fn spec(self) -> &'static ThemeSpec {
        match self {
            Self::Github => &GITHUB,
            Self::OneLight => &ONE_LIGHT,
        }
    }

    fn index(self) -> usize {
        match self {
            Self::Github => 0,
            Self::OneLight => 1,
        }
    }
}

/// A theme as data: the base foreground every unscoped token inherits, and a
/// scope-selector → colour table. Built into a syntect [`Theme`] once per
/// process.
struct ThemeSpec {
    name: &'static str,
    base: Rgb,
    /// `(scope selector, colour)`; deeper selectors win inside syntect's own
    /// scoring, so list order is not load-bearing.
    rules: &'static [(&'static str, Rgb)],
}

/// GitHub light syntax colours (`github` tmTheme).
const GITHUB: ThemeSpec = ThemeSpec {
    name: "github",
    base: Rgb::new(0x24, 0x29, 0x2e),
    rules: &[
        ("comment", Rgb::new(0x6a, 0x73, 0x7d)),
        ("string", Rgb::new(0x03, 0x2f, 0x62)),
        ("constant.numeric", Rgb::new(0x00, 0x5c, 0xc5)),
        ("constant.language", Rgb::new(0x00, 0x5c, 0xc5)),
        ("constant.character.escape", Rgb::new(0x00, 0x5c, 0xc5)),
        ("constant.other", Rgb::new(0x00, 0x5c, 0xc5)),
        ("support.constant", Rgb::new(0x00, 0x5c, 0xc5)),
        ("entity.name.function", Rgb::new(0x00, 0x5c, 0xc5)),
        ("support.function", Rgb::new(0x00, 0x5c, 0xc5)),
        ("entity.name.class", Rgb::new(0x6f, 0x42, 0xc1)),
        ("entity.name.type", Rgb::new(0x6f, 0x42, 0xc1)),
        ("support.class", Rgb::new(0x6f, 0x42, 0xc1)),
        ("support.type", Rgb::new(0x6f, 0x42, 0xc1)),
        ("keyword", Rgb::new(0xd7, 0x3a, 0x49)),
        ("storage", Rgb::new(0xd7, 0x3a, 0x49)),
        ("entity.name.tag", Rgb::new(0x22, 0x86, 0x3a)),
        ("entity.other.attribute-name", Rgb::new(0x6f, 0x42, 0xc1)),
        ("invalid", Rgb::new(0xb3, 0x1d, 0x28)),
        ("markup.inserted", Rgb::new(0x22, 0x86, 0x3a)),
        ("markup.deleted", Rgb::new(0xb3, 0x1d, 0x28)),
        ("markup.changed", Rgb::new(0xe3, 0x62, 0x09)),
        ("markup.raw", Rgb::new(0x03, 0x2f, 0x62)),
    ],
};

/// Atom's One Light syntax colours.
const ONE_LIGHT: ThemeSpec = ThemeSpec {
    name: "one-light",
    base: Rgb::new(0x38, 0x3a, 0x42),
    rules: &[
        ("comment", Rgb::new(0xa0, 0xa1, 0xa7)),
        ("string", Rgb::new(0x50, 0xa1, 0x4f)),
        ("constant.numeric", Rgb::new(0x98, 0x68, 0x01)),
        ("constant.language", Rgb::new(0x98, 0x68, 0x01)),
        ("constant.character.escape", Rgb::new(0x98, 0x68, 0x01)),
        ("constant.other", Rgb::new(0x98, 0x68, 0x01)),
        ("support.constant", Rgb::new(0x98, 0x68, 0x01)),
        ("entity.name.function", Rgb::new(0x40, 0x78, 0xf2)),
        ("support.function", Rgb::new(0x40, 0x78, 0xf2)),
        ("entity.name.class", Rgb::new(0xc1, 0x84, 0x01)),
        ("entity.name.type", Rgb::new(0xc1, 0x84, 0x01)),
        ("support.class", Rgb::new(0xc1, 0x84, 0x01)),
        ("support.type", Rgb::new(0xc1, 0x84, 0x01)),
        ("keyword", Rgb::new(0xa6, 0x26, 0xa4)),
        ("storage", Rgb::new(0xa6, 0x26, 0xa4)),
        ("entity.name.tag", Rgb::new(0xe4, 0x56, 0x49)),
        ("entity.other.attribute-name", Rgb::new(0x98, 0x68, 0x01)),
        ("invalid", Rgb::new(0xe4, 0x56, 0x49)),
        ("markup.inserted", Rgb::new(0x50, 0xa1, 0x4f)),
        ("markup.deleted", Rgb::new(0xe4, 0x56, 0x49)),
        ("markup.changed", Rgb::new(0x98, 0x68, 0x01)),
        ("markup.raw", Rgb::new(0x50, 0xa1, 0x4f)),
    ],
};

/// Author-facing spellings → syntax names in the dump. Keys are already
/// lowercased; lookup still falls back to the raw token so `C++`/`MATLAB`
/// (case-insensitive name match) work without an entry.
const ALIASES: &[(&str, &str)] = &[
    ("py", "Python"),
    ("python3", "Python"),
    ("rs", "Rust"),
    ("js", "JavaScript"),
    ("jsx", "JSX"),
    ("ts", "TypeScript"),
    ("tsx", "TSX"),
    ("tex", "LaTeX"),
    ("latex", "LaTeX"),
    ("sh", "Bash"),
    ("zsh", "Bash"),
    ("shell", "Bash"),
    ("bash", "Bash"),
    ("md", "Markdown"),
    ("markdown", "Markdown"),
    ("dot", "Graphviz (DOT)"),
    ("gv", "Graphviz (DOT)"),
    ("graphviz", "Graphviz (DOT)"),
    ("git", "Git Diff"),
    ("yml", "YAML"),
    ("c++", "C++"),
    ("cc", "C++"),
    ("make", "Makefile"),
    ("mk", "Makefile"),
    ("rb", "Ruby"),
];

/// `lang` values that deliberately mean "plain monospace, no highlighting" —
/// the author's explicit choice, so no warning is emitted for them.
const PLAIN_LANGS: &[&str] = &["", "text", "txt", "plaintext"];

/// The curated syntax set, loaded once per process. The result is cached as a
/// `Result` so a failed load is reported once as a build error instead of
/// panicking in a `Lazy` initializer.
static SYNTAX_SET: OnceLock<Result<SyntaxSet, String>> = OnceLock::new();

/// Built themes, one slot per [`HighlightTheme`].
static THEMES: [OnceLock<Theme>; 2] = [OnceLock::new(), OnceLock::new()];

fn syntax_set() -> Result<&'static SyntaxSet> {
    let loaded = SYNTAX_SET.get_or_init(|| {
        syntect::dumps::from_reader(Cursor::new(SYNTAXES)).map_err(|e| {
            format!(
                "code listing assets failed to load ({e}) — regenerate with scripts/regen-syntaxes"
            )
        })
    });
    match loaded {
        Ok(set) => Ok(set),
        Err(message) => Err(anyhow!(message.clone())),
    }
}

fn theme_of(kind: HighlightTheme) -> &'static Theme {
    THEMES[kind.index()].get_or_init(|| {
        let spec = kind.spec();
        let scopes = spec
            .rules
            .iter()
            .map(|(selector, rgb)| ThemeItem {
                scope: selector
                    .parse()
                    .expect("theme scope selectors are compile-time constants"),
                style: StyleModifier {
                    foreground: Some((*rgb).into()),
                    background: None,
                    font_style: None,
                },
            })
            .collect();
        Theme {
            name: Some(spec.name.to_string()),
            author: Some("texforge".to_string()),
            settings: ThemeSettings {
                foreground: Some(spec.base.into()),
                background: Some(Color {
                    r: 255,
                    g: 255,
                    b: 255,
                    a: 255,
                }),
                ..ThemeSettings::default()
            },
            scopes,
        }
    })
}

/// Tokenize one block.
///
/// * `Ok(Some(lines))` — one `Vec<Span>` per line of `code` (same line
///   splitting emit.rs uses), coloured or plain-base.
/// * `Ok(None)` — the language is unknown; the caller warns (W1) and renders
///   monochrome. Never a build failure.
/// * `Err` — the committed asset itself could not be loaded (a real bug:
///   regenerate the asset).
pub fn highlight(lang: &str, code: &str, theme: HighlightTheme) -> Result<Option<Vec<Vec<Span>>>> {
    let raw = lang.trim();
    let lower = raw.to_lowercase();
    if PLAIN_LANGS.contains(&lower.as_str()) {
        // Deliberate plain block: no syntect call, no warning.
        return Ok(Some(monochrome(code)));
    }

    let set = syntax_set()?;
    let alias = ALIASES
        .iter()
        .find(|(from, _)| *from == lower)
        .map(|(_, to)| *to)
        .unwrap_or(&lower);
    let syntax = set
        .find_syntax_by_token(alias)
        .or_else(|| set.find_syntax_by_token(raw));
    let Some(syntax) = syntax else {
        return Ok(None);
    };

    Ok(Some(tokenize(set, syntax, code, theme)))
}

/// One plain span per line — the shape a monochrome block needs.
fn monochrome(code: &str) -> Vec<Vec<Span>> {
    code.split('\n')
        .map(|line| {
            vec![Span {
                text: line.to_string(),
                color: None,
            }]
        })
        .collect()
}

/// Tokenize with one [`HighlightLines`] for the whole block, so multi-line
/// state (block comments, heredocs, triple-quoted strings) carries across
/// lines.
///
/// Highlighting must never fail a build: both a syntect error **and** a
/// pattern the bundled regex engine cannot compile degrade the whole block to
/// monochrome, with a warning on stderr. The second case surfaces as a panic
/// inside syntect (`regex string should be pre-tested`) — grammars are
/// validated at regen time (`scripts/regen-syntaxes`), so this is the
/// backstop, not the mechanism.
fn tokenize(
    set: &SyntaxSet,
    syntax: &SyntaxReference,
    code: &str,
    kind: HighlightTheme,
) -> Vec<Vec<Span>> {
    // Silence the default panic hook for the duration of the catch: syntect's
    // raw message would alarm a user whose build actually succeeded. The
    // warning printed below is the user-facing text.
    let previous_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));
    let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        tokenize_lines(set, syntax, code, kind)
    }));
    std::panic::set_hook(previous_hook);

    match outcome {
        Ok(Ok(lines)) => lines,
        Ok(Err(message)) => {
            eprintln!(
                "warning: syntax highlighting failed for '{}' ({message}) — rendered without \
                 highlighting",
                syntax.name
            );
            monochrome(code)
        }
        Err(_) => {
            eprintln!(
                "warning: '{}' uses a pattern the bundled highlighter cannot run — rendered \
                 without highlighting",
                syntax.name
            );
            monochrome(code)
        }
    }
}

fn tokenize_lines(
    set: &SyntaxSet,
    syntax: &SyntaxReference,
    code: &str,
    kind: HighlightTheme,
) -> Result<Vec<Vec<Span>>, String> {
    let theme = theme_of(kind);
    let base: Rgb = theme.settings.foreground.unwrap_or(Color::BLACK).into();
    let mut state = HighlightLines::new(syntax, theme);
    // Lines are fed to syntect with their trailing newline (the syntax set is
    // loaded that way, which is syntect's recommended shape).
    let mut lines = Vec::new();
    for line in code.split('\n') {
        let mut owned = String::with_capacity(line.len() + 1);
        owned.push_str(line);
        owned.push('\n');
        let spans = state
            .highlight_line(&owned, set)
            .map_err(|e| e.to_string())?;
        let mut mapped: Vec<Span> = spans
            .iter()
            .map(|(style, text)| Span {
                text: (*text).to_string(),
                color: {
                    let rgb = Rgb::from(style.foreground);
                    (rgb != base).then_some(rgb)
                },
            })
            .collect();
        // syntect keeps the newline it was fed inside the last span; emit.rs
        // owns line separation, so drop it here or it would land as a literal
        // newline inside a LaTeX paragraph.
        if let Some(last) = mapped.last_mut() {
            if let Some(trimmed) = last.text.strip_suffix('\n') {
                last.text.truncate(trimmed.len());
            }
        }
        lines.push(mapped);
    }
    Ok(lines)
}

/// Language → one-liner samples used by the closure test below. Every sample
/// must produce at least one coloured span: that is what catches a dump with
/// a missing embedded syntax (the T7 trap), because a dangling reference
/// surfaces as a parse error and the block would fall back to monochrome.
#[cfg(test)]
pub(crate) const SAMPLES: &[(&str, &str)] = &[
    ("bash", "# comment\necho \"hi\""),
    ("c", "int x = 1; // comment"),
    ("c++", "int x = 1; // comment"),
    ("clojure", "; comment\n(def x 1)"),
    ("css", "/* comment */\na { color: red; }"),
    ("diff", "--- a\n+++ b\n+added"),
    ("erlang", "% comment\nf() -> ok."),
    ("go", "package main // comment"),
    ("dot", "digraph G { a -> b }"),
    ("html", "<html><!-- comment --></html>"),
    ("haskell", "-- comment\nf x = x"),
    ("json", "{\"a\": 1}"),
    ("java", "class A { int x = 1; } // c"),
    ("js", "function f() { return 'x'; } // c"),
    ("ts", "const x: number = 1; // c"),
    ("tex", "% comment\n\\documentclass{article}"),
    ("lua", "-- comment\nlocal x = 1"),
    ("make", "# comment\ntarget:\n\techo hi"),
    ("md", "# heading\n\n```python\nx = 1\n```"),
    ("matlab", "% comment\nx = 1;"),
    ("ocaml", "(* comment *)\nlet x = 1"),
    ("php", "<?php // comment\n$x = 1;"),
    ("python", "def fib(n):\n    return n  # comment"),
    ("r", "# comment\nx <- 1"),
    ("rb", "# comment\nputs 'hi'"),
    ("rs", "fn main() { let x = 1; } // c"),
    ("sql", "SELECT 1; -- comment"),
    ("toml", "# comment\nkey = \"value\""),
    ("xml", "<?xml version=\"1.0\"?><!-- c -->"),
    ("yml", "# comment\nkey: value"),
];

#[cfg(test)]
mod tests {
    use super::*;

    fn render(lang: &str, code: &str) -> Option<Vec<Vec<Span>>> {
        highlight(lang, code, HighlightTheme::Github).unwrap()
    }

    #[test]
    fn unknown_language_is_none_not_an_error() {
        assert!(render("brainfuck", "+++").is_none());
        assert!(render("Brainfuck 9000", "+++").is_none());
        // `kt` (Kotlin) ships no grammar and is not a documented alias: like
        // every undocumented spelling it must warn, not resolve to plain text.
        assert!(render("kt", "fun main() {}").is_none());
    }

    #[test]
    fn plain_languages_are_explicitly_monochrome() {
        for lang in ["", "text", "txt", "plaintext", "  Txt "] {
            let lines = render(lang, "a\nb").expect("plain langs must resolve");
            assert_eq!(lines.len(), 2);
            assert!(lines.iter().flatten().all(|s| s.color.is_none()));
        }
    }

    #[test]
    fn python_produces_coloured_runs() {
        let lines = render("python", "def fib(n):  # comment").expect("python resolves");
        assert!(
            lines.iter().flatten().any(|s| s.color.is_some()),
            "expected at least one coloured span"
        );
    }

    #[test]
    fn aliases_resolve_to_the_shipped_syntax() {
        for (lang, expect) in [
            ("js", "JavaScript"),
            ("py", "Python"),
            ("rs", "Rust"),
            ("sh", "Bash"),
            ("zsh", "Bash"),
            ("md", "Markdown"),
            ("yml", "YAML"),
        ] {
            let lines = render(lang, "x = 1 // c").unwrap_or_else(|| panic!("{lang} must resolve"));
            assert!(!lines.is_empty());
            let _ = expect;
        }
        // Raw, case-sensitive-ish spellings still work through name matching.
        assert!(render("C++", "int x;").is_some());
    }

    /// Every `lang=` value (and alias) `docs/listings.md` publishes must
    /// resolve to a shipped syntax — an undocumented-then-unresolved spelling
    /// would silently render monochrome with a warning.
    #[test]
    fn documented_lang_spellings_resolve() {
        let documented = [
            "python",
            "py",
            "rust",
            "rs",
            "javascript",
            "js",
            "typescript",
            "ts",
            "bash",
            "sh",
            "zsh",
            "shell",
            "c",
            "c++",
            "cpp",
            "cc",
            "json",
            "yaml",
            "yml",
            "toml",
            "markdown",
            "md",
            "latex",
            "tex",
            "r",
            "sql",
            // the doc claims `sql` also matches "by name"
            "mysql",
            "postgresql",
            "clojure",
            "css",
            "diff",
            "erlang",
            "go",
            "haskell",
            "java",
            "lua",
            "matlab",
            "ocaml",
            "php",
            "ruby",
            "rb",
            "xml",
            "make",
            "mk",
            "dot",
            "graphviz",
            "gv",
            "git",
            "jsx",
            "tsx",
            // deliberate plain blocks: resolve without a warning, not to a grammar
            "text",
            "txt",
            "plaintext",
        ];
        for lang in documented {
            let resolved = highlight(lang, "x = 1 // c", HighlightTheme::Github)
                .unwrap_or_else(|e| panic!("{lang}: asset failed to load: {e}"));
            assert!(resolved.is_some(), "lang={lang} does not resolve");
        }
    }

    /// The T7 closure test: every curated language must tokenize its sample
    /// with colour — a dump missing an embedded syntax degrades to
    /// monochrome here instead of silently shipping.
    #[test]
    fn every_curated_language_tokenizes_with_colour() {
        for (lang, sample) in SAMPLES {
            let lines = highlight(lang, sample, HighlightTheme::Github)
                .unwrap_or_else(|e| panic!("{lang}: asset failed to load: {e}"));
            let lines = lines.unwrap_or_else(|| panic!("{lang} did not resolve to a syntax"));
            assert_eq!(
                lines.len(),
                sample.split('\n').count(),
                "{lang}: line count must match the input"
            );
            assert!(
                lines.iter().flatten().any(|s| s.color.is_some()),
                "{lang}: expected colour for sample {sample:?}"
            );
        }
    }

    #[test]
    fn round_trip_of_every_sample_survives_the_one_light_theme() {
        // The second theme must tokenize the same inputs; it only differs in
        // colours, but a broken selector would fail parsing for both.
        for (lang, sample) in SAMPLES {
            assert!(
                highlight(lang, sample, HighlightTheme::OneLight)
                    .unwrap_or_else(|e| panic!("{lang}: {e}"))
                    .is_some(),
                "{lang}"
            );
        }
    }

    #[test]
    fn theme_parse_names_and_error() {
        assert_eq!(
            HighlightTheme::parse("github").unwrap(),
            HighlightTheme::Github
        );
        assert_eq!(
            HighlightTheme::parse("one-light").unwrap(),
            HighlightTheme::OneLight
        );
        let err = HighlightTheme::parse("dracula").unwrap_err().to_string();
        assert!(err.contains("dracula"), "{err}");
        for name in VALID_THEME_NAMES {
            assert!(err.contains(name), "{err}");
        }
    }

    #[test]
    fn rgb_names_and_fractions() {
        let rgb = Rgb::new(0x03, 0x2f, 0x62);
        assert_eq!(rgb.name(), "tfxcol032f62");
        assert_eq!(rgb.to_rgb_list(), "0.012,0.184,0.384");
        assert_eq!(
            Rgb::new(0x6e, 0x77, 0x81).to_rgb_list(),
            "0.431,0.467,0.506"
        );
    }

    #[test]
    fn line_splitting_matches_emit() {
        // emit.rs renders `body.split('\n')`; the tokenizer must yield one
        // entry per element, blank lines included.
        let lines = highlight("python", "a\n\nb", HighlightTheme::Github)
            .unwrap()
            .unwrap();
        assert_eq!(lines.len(), 3);
        assert!(lines[1].iter().all(|s| s.text == "\n" || s.text.is_empty()));
    }
}
