name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths: [Cargo.toml]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: UniverLab/workflows/.github/workflows/rust-release.yml@main
    with:
      binary-name: texforge
    secrets: inherit
